### ISSUE TITLE
crahses when trying to open any manga and trying to see about

### ISSUE THREAD

**Issue by alidan** [nekomangaorg/Neko#1860] opened 2024-06-28 02:10 UTC
### Steps to reproduce

try to open about 

try to open a manga

### Expected behavior

see what version im on and open manga

### Actual behavior

crash

### Crash logs

![Screenshot_20240627_205937](https://github.com/nekomangaorg/Neko/assets/2681758/e63585d1-c61f-43c5-a4df-4e76e70d7de4)
![Screenshot_20240627_205943](https://github.com/nekomangaorg/Neko/assets/2681758/9fb15f1d-be2c-46e6-811e-6385fff2b6b4)
![Screenshot_20240627_205928](https://github.com/nekomangaorg/Neko/assets/2681758/17c77417-b3df-4e1a-9905-446c442e37c1)
[neko_crash_logs.txt](https://github.com/user-attachments/files/16023246/neko_crash_logs.txt)

### Neko version

I think it updated to the newest version but I can't check without crashing

### Android version

android 13 

### Device

galaxy tab s7+

### Other details

I enabled verbose logging, closed app, reopened, clicked a manga, and dumped from that, the screenshots were from a seperate one

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to the newest version **[Latest](https://github.com/nekomangaorg/Neko/releases/latest)**.
- [X] I have filled out all of the requested information in this form.

**Comment by Exia1987** [comment] 2024-06-28 04:04
Same problem but on Samsung S6.

**Comment by Wolf-ON** [comment] 2024-06-28 08:41
Duplicate of closed #1857 

You could check by reading first line of crash log: `App version: 2.16.8`

You need to (probably manually) update Neko to Latest (2.16.9) version (there was hotfix 7 hours ago)

**Comment by nonproto** [comment] 2024-06-28 08:58
Manually update to 2.16.9

**Closed** 2024-06-28 08:58 UTC
Labels: bug
